sonata_admin:
    title: 'Capharnaum'
    # title_logo: /images/logos/logo_sonata.png
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        legacy_twig_text_extension: false

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
